import { useState, type FormEvent } from 'react'
import type { AdminClient } from '../api/admin-client'

export function AdminAccountPage({ client, displayName, onLogout }: { client: AdminClient, displayName: string, onLogout?: () => Promise<void> }) {
  const [name, setName] = useState(displayName); const [currentPassword, setCurrentPassword] = useState(''); const [newPassword, setNewPassword] = useState(''); const [message, setMessage] = useState(''); const [pending, setPending] = useState(false)
  const updateName = async (event: FormEvent) => { event.preventDefault(); setPending(true); setMessage(''); try { await client.updateSelf({ displayName: name, currentPassword }); setCurrentPassword(''); setMessage('显示名称已更新') } catch (error) { setMessage(error instanceof Error ? error.message : '更新失败') } finally { setPending(false) } }
  const changePassword = async (event: FormEvent) => { event.preventDefault(); setPending(true); setMessage(''); try { await client.changeOwnPassword({ currentPassword, newPassword }); setCurrentPassword(''); setNewPassword(''); await onLogout?.() } catch (error) { setMessage(error instanceof Error ? error.message : '密码修改失败') } finally { setPending(false) } }
  return <section className="page-section"><div className="page-heading"><div><p>账号安全</p><h1>我的账号</h1></div></div>{message ? <p role="status">{message}</p> : null}<form className="panel form-stack" onSubmit={(event) => void updateName(event)}><h2>显示名称</h2><label>显示名称<input required maxLength={100} value={name} onChange={(event) => setName(event.target.value)} /></label><label>当前密码<input required type="password" autoComplete="current-password" value={currentPassword} onChange={(event) => setCurrentPassword(event.target.value)} /></label><button disabled={pending}>保存名称</button></form><form className="panel form-stack" onSubmit={(event) => void changePassword(event)}><h2>修改密码</h2><label>当前密码<input required type="password" autoComplete="current-password" value={currentPassword} onChange={(event) => setCurrentPassword(event.target.value)} /></label><label>新密码<input required minLength={12} type="password" autoComplete="new-password" value={newPassword} onChange={(event) => setNewPassword(event.target.value)} /></label><button disabled={pending}>修改密码并退出全部设备</button></form></section>
}
