import { useEffect, useMemo, useState } from 'react'
import { Link } from 'react-router-dom'
import type { AdminApplicationListItem, AdminClient } from '../api/admin-client'
import { BulkStatusDialog } from '../features/applications/BulkStatusDialog'

const statuses = ['', 'submitted', 'reviewing', 'needs_supplement', 'admitted', 'waitlisted', 'rejected']
const bulkStatuses = ['reviewing', 'admitted', 'waitlisted', 'rejected']

export function ApplicationsPage({ client }: { client: AdminClient }) {
  const [filters, setFilters] = useState({ status: '', search: '', organization: '', identityType: '', educationStage: '', submittedFrom: '', submittedTo: '', page: 1 })
  const [items, setItems] = useState<AdminApplicationListItem[]>([]); const [total, setTotal] = useState(0); const [loading, setLoading] = useState(true); const [error, setError] = useState('')
  const [selected, setSelected] = useState<Set<string>>(new Set()); const [bulkTarget, setBulkTarget] = useState(''); const [showBulk, setShowBulk] = useState(false); const [pending, setPending] = useState(false); const [result, setResult] = useState('')
  const query = useMemo(() => { const value = new URLSearchParams({ page: String(filters.page), pageSize: '20', sort: 'submittedAt_desc' }); for (const key of ['status', 'search', 'organization', 'identityType', 'educationStage', 'submittedFrom', 'submittedTo'] as const) if (filters[key]) value.set(key, filters[key]); return value }, [filters])
  const load = async () => { setLoading(true); setError(''); try { const response = await client.listApplications(query); setItems(response.data.items); setTotal(response.data.total); setSelected(new Set()) } catch (caught) { setError(caught instanceof Error ? caught.message : '加载失败') } finally { setLoading(false) } }
  useEffect(() => { void load() }, [query.toString()])
  const update = (key: keyof typeof filters, value: string | number) => setFilters((current) => ({ ...current, [key]: value, ...(key === 'page' ? {} : { page: 1 }) }))
  const exportCsv = async () => { try { const blob = await client.exportApplications(query); const url = URL.createObjectURL(blob); const link = document.createElement('a'); link.href = url; link.download = '实训营报名名单.csv'; link.click(); URL.revokeObjectURL(url) } catch (caught) { setError(caught instanceof Error ? caught.message : '导出失败') } }
  const bulk = async () => { setPending(true); try { const response = await client.bulkTransitionApplications({ applicationIds: [...selected], targetStatus: bulkTarget }); const succeeded = response.data.results.filter((item) => item.success).length; setResult(`成功 ${succeeded} 份，失败 ${response.data.results.length - succeeded} 份`); setShowBulk(false); await load() } catch (caught) { setError(caught instanceof Error ? caught.message : '批量操作失败') } finally { setPending(false) } }
  return <section>
    <header className="admin-page-header"><div><h1>报名审核</h1><p>共 {total} 份符合当前筛选条件的报名</p></div><button type="button" onClick={() => void exportCsv()}>导出当前筛选</button></header>
    <div className="application-filters"><label>状态<select value={filters.status} onChange={(event) => update('status', event.target.value)}>{statuses.map((status) => <option key={status} value={status}>{status || '全部'}</option>)}</select></label><label>搜索<input value={filters.search} maxLength={100} placeholder="姓名、手机号或单位" onChange={(event) => update('search', event.target.value)} /></label><label>单位<input value={filters.organization} maxLength={200} onChange={(event) => update('organization', event.target.value)} /></label><label>身份<input value={filters.identityType} maxLength={100} onChange={(event) => update('identityType', event.target.value)} /></label><label>学历<input value={filters.educationStage} maxLength={100} onChange={(event) => update('educationStage', event.target.value)} /></label><label>提交起始<input type="datetime-local" onChange={(event) => update('submittedFrom', event.target.value ? new Date(event.target.value).toISOString() : '')} /></label><label>提交截止<input type="datetime-local" onChange={(event) => update('submittedTo', event.target.value ? new Date(event.target.value).toISOString() : '')} /></label></div>
    {error ? <p role="alert">{error}</p> : null}{result ? <p role="status">{result}</p> : null}{loading ? <p role="status">正在加载报名</p> : items.length === 0 ? <p>暂无符合条件的报名。</p> : <table><thead><tr><th>选择</th><th>姓名</th><th>单位</th><th>身份/学历</th><th>状态</th><th>提交时间</th><th>操作</th></tr></thead><tbody>{items.map((item) => <tr key={item.id}><td><input aria-label={`选择 ${item.name}`} type="checkbox" checked={selected.has(item.id)} onChange={(event) => setSelected((current) => { const next = new Set(current); if (event.target.checked) next.add(item.id); else next.delete(item.id); return next })} /></td><td>{item.name}</td><td>{item.organization}</td><td>{item.identityType} / {item.educationStage}</td><td>{item.status}</td><td>{item.submittedAt ? new Date(item.submittedAt).toLocaleString('zh-CN') : '—'}</td><td><Link to={`/applications/${item.id}`}>查看审核</Link></td></tr>)}</tbody></table>}
    <div className="admin-actions"><select aria-label="批量目标状态" value={bulkTarget} onChange={(event) => setBulkTarget(event.target.value)}><option value="">选择目标状态</option>{bulkStatuses.map((status) => <option key={status}>{status}</option>)}</select><button type="button" disabled={!bulkTarget || selected.size === 0} onClick={() => setShowBulk(true)}>批量调整（{selected.size}）</button><button type="button" disabled={filters.page <= 1} onClick={() => update('page', filters.page - 1)}>上一页</button><button type="button" disabled={filters.page * 20 >= total} onClick={() => update('page', filters.page + 1)}>下一页</button></div>
    {showBulk ? <BulkStatusDialog count={selected.size} targetStatus={bulkTarget} pending={pending} onCancel={() => setShowBulk(false)} onConfirm={bulk} /> : null}
  </section>
}
