import { useEffect, useState } from 'react'
import { Link, useParams } from 'react-router-dom'
import type { AdminApplicationDetail, AdminClient } from '../api/admin-client'
const nextStatuses: Record<string, string[]> = { submitted: ['reviewing'], reviewing: ['needs_supplement', 'admitted', 'waitlisted', 'rejected'], needs_supplement: ['reviewing'] }
export function ApplicationReviewPage({ client }: { client: AdminClient }) {
  const { id = '' } = useParams(); const [detail, setDetail] = useState<AdminApplicationDetail | null>(null); const [error, setError] = useState(''); const [pending, setPending] = useState(false); const [target, setTarget] = useState(''); const [publicMessage, setPublicMessage] = useState(''); const [internalNote, setInternalNote] = useState(''); const [deadline, setDeadline] = useState(''); const [fields, setFields] = useState<Set<string>>(new Set()); const [slots, setSlots] = useState<Set<string>>(new Set())
  const load = async () => { try { const response = await client.getApplication(id); setDetail(response.data); setInternalNote(response.data.application.internalReviewNote ?? '') } catch (caught) { setError(caught instanceof Error ? caught.message : '加载失败') } }
  useEffect(() => { void load() }, [id])
  useEffect(() => { if (detail) setTarget(nextStatuses[detail.application.status]?.[0] ?? '') }, [detail?.application.status])
  if (error) return <p role="alert">{error}</p>; if (!detail) return <p role="status">正在加载报名详情</p>
  const app = detail.application; const latest = detail.versions[0]?.snapshot as Record<string, unknown> | undefined; const allowed = nextStatuses[app.status] ?? []
  const toggle = (set: Set<string>, value: string, update: (next: Set<string>) => void) => { const next = new Set(set); if (next.has(value)) next.delete(value); else next.add(value); update(next) }
  const transition = async () => { setPending(true); setError(''); try { await client.transitionApplication(id, { expectedRevision: app.revision, targetStatus: target, publicMessage: target === 'needs_supplement' ? publicMessage : undefined, internalNote, supplementDeadline: deadline ? new Date(deadline).toISOString() : undefined, editableFieldIds: [...fields], editableAttachmentIds: [...slots] }); await load(); setTarget('') } catch (caught) { setError(caught instanceof Error ? caught.message : '状态更新失败') } finally { setPending(false) } }
  return <section><p><Link to="/applications">← 返回报名列表</Link></p><h1>{app.name}的报名</h1><dl><dt>状态</dt><dd>{app.status}</dd><dt>手机号</dt><dd>{app.phone}</dd><dt>单位</dt><dd>{app.organization}</dd><dt>身份与学历</dt><dd>{app.identityType} / {app.educationStage}</dd><dt>提交时间</dt><dd>{app.submittedAt ?? '—'}</dd></dl><section><h2>固定资料</h2>{Object.entries((latest?.profile ?? app.coreFields) as Record<string, unknown>).map(([key, value]) => <p key={key}><strong>{key}：</strong>{String(value)}</p>)}</section><section><h2>报名答案（只读）</h2>{Object.entries((latest?.answers ?? app.answers) as Record<string, unknown>).map(([key, value]) => <p key={key}><strong>{app.form.questions.find((q) => q.id === key)?.label ?? key}：</strong>{Array.isArray(value) ? value.join('、') : String(value)}</p>)}</section><section><h2>附件</h2>{detail.attachments.length ? <ul>{detail.attachments.map((file) => <li key={file.id}><a href={file.downloadUrl}>{file.originalName}</a>（{file.sizeBytes} 字节）</li>)}</ul> : <p>无附件</p>}</section><section><h2>状态历史</h2><ol>{detail.history.map((entry) => <li key={`${entry.createdAt}-${entry.toStatus}`}>{new Date(entry.createdAt).toLocaleString('zh-CN')}：{entry.fromStatus ?? '创建'} → {entry.toStatus}{entry.reason ? `（${entry.reason}）` : ''}</li>)}</ol></section>
    {allowed.length ? <section><h2>审核操作</h2><label>目标状态<select value={target} onChange={(e) => setTarget(e.target.value)}><option value="">请选择</option>{allowed.map((status) => <option key={status}>{status}</option>)}</select></label><label>内部备注<textarea value={internalNote} maxLength={2000} onChange={(e) => setInternalNote(e.target.value)} /></label>{target === 'needs_supplement' ? <div><label>面向学员的说明<textarea required value={publicMessage} maxLength={2000} onChange={(e) => setPublicMessage(e.target.value)} /></label><label>补充截止时间<input type="datetime-local" value={deadline} onChange={(e) => setDeadline(e.target.value)} /></label><fieldset><legend>允许修改的资料</legend>{['name', 'email', 'organization', 'department', 'identityType', 'educationStage', 'majorResearchDirection', ...app.form.questions.filter((q) => q.active).map((q) => q.id)].map((key) => <label key={key}><input type="checkbox" checked={fields.has(key)} onChange={() => toggle(fields, key, setFields)} />{app.form.questions.find((q) => q.id === key)?.label ?? key}</label>)}</fieldset><fieldset><legend>允许替换的附件</legend>{app.form.attachments.filter((slot) => slot.active).map((slot) => <label key={slot.id}><input type="checkbox" checked={slots.has(slot.id)} onChange={() => toggle(slots, slot.id, setSlots)} />{slot.label}</label>)}</fieldset></div> : null}<button type="button" disabled={pending || !target} onClick={() => void transition()}>{pending ? '提交中' : '确认更新状态'}</button></section> : <p>当前状态没有可执行的后续审核操作。</p>}</section>
}
