import { useEffect, useState, type FormEvent } from 'react'
import type { AdminClient, StudentAccount } from '../api/admin-client'

export function StudentAccountsPage({ client }: { client: AdminClient }) {
  const [items, setItems] = useState<StudentAccount[]>([]); const [search, setSearch] = useState(''); const [password, setPassword] = useState(''); const [message, setMessage] = useState(''); const [pending, setPending] = useState(false)
  const load = async (value = search) => { const response = await client.listStudents(value); setItems(response.data.students) }
  useEffect(() => { void load('') }, [client])
  const submit = (event: FormEvent) => { event.preventDefault(); void load() }
  const mutate = async (item: StudentAccount, kind: 'status' | 'reset') => { if (!password || pending || !window.confirm(`确认操作学员账号：${item.displayName}？`)) return; setPending(true); setMessage(''); try { if (kind === 'status') await client.setStudentStatus(item.id, { currentPassword: password, disabled: !item.disabledAt }); else await client.forceStudentPasswordReset(item.id, { currentPassword: password }); setPassword(''); await load(); setMessage(kind === 'reset' ? '已撤销会话；学员须通过现有验证码流程重置密码' : '账号状态已更新') } catch (error) { setMessage(error instanceof Error ? error.message : '操作失败') } finally { setPending(false) } }
  return <section className="page-section"><div className="page-heading"><div><p>权限与账号</p><h1>学员账号</h1></div></div>{message ? <p role="status">{message}</p> : null}<form className="panel form-grid" onSubmit={submit}><label>搜索姓名或手机号<input value={search} onChange={(event) => setSearch(event.target.value)} /></label><button>搜索</button><label>当前管理员密码<input type="password" autoComplete="current-password" value={password} onChange={(event) => setPassword(event.target.value)} /></label></form><div className="panel table-scroll"><table><thead><tr><th>姓名</th><th>手机号</th><th>状态</th><th>创建时间</th><th>操作</th></tr></thead><tbody>{items.map((item) => <tr key={item.id}><td>{item.displayName}</td><td>{item.phone}</td><td>{item.disabledAt ? '已停用' : '有效'}</td><td>{new Date(item.createdAt).toLocaleString('zh-CN')}</td><td><div className="button-row"><button disabled={pending || !password} onClick={() => void mutate(item, 'status')}>{item.disabledAt ? '启用' : '停用'}</button><button disabled={pending || !password || Boolean(item.disabledAt)} onClick={() => void mutate(item, 'reset')}>要求验证码重置</button></div></td></tr>)}</tbody></table></div></section>
}
